# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# Just for troubleshooting
# init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# version format
version: 0.1.{build}-alpha

# branches:
  # whitelist
  # only:
  # - master
  # - development

image: Visual Studio 2015

clone_depth: 10

skip_tags: true

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  
before_build:
  - nuget restore src\YTMusicDownloader.sln -SolutionDirectory src\
    
#---------------------------------#
#       build configuration       #
#---------------------------------#

platform:
  - x86

environment:
  certPw:
    secure: 2kdLShlG5xH4zfyfUpnNh72X88QTzA0Jm0ctQeMtO9fnQRC11I9awTfu+9WKyMAryNbTuCtfLuV22V7yxIQ0hZJNvqOgiTJR7j7rNKB722E=
  certSalt:
    secure: s9dnDaZCR8REfFgb7OvvcKueaHsfBWpOJJag3on99LjZ2TIxk1e3j/nM7k0guMv1A3RJvJj/QbcBXFxtL7VQLBynIOUe1qgN4hFvMk+pp3I=
  signtoolLocation: C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin\signtool.exe

configuration: Release

build:
  verbosity: normal
  project: src\YTMusicDownloader\YTMusicDownloader.csproj

after_build:
  - ps: .\buildScripts\signApp.ps1 -certFile ..\cert\TestCert.pfx -outputDir src\YTMusicDownloader\bin\x86
    
artifacts:
  - path: src\YTMusicDownloader\bin\x86\$(configuration)
    name: YTMusicDownloader_portable_x86
    type: zip

#test: off
